# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grocery.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rgrocery.proto\x12\x07grocery\"\x1c\n\x05Query\x12\x13\n\x0bsearch_term\x18\x01 \x01(\t\"\x8d\x01\n\x07Results\x12*\n\x08products\x18\x04 \x03(\x0b\x32\x18.grocery.Results.Product\x1aV\n\x07Product\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\r\n\x05image\x18\x04 \x01(\t\x12\r\n\x05price\x18\x05 \x01(\x02\x32:\n\x07Grocery\x12/\n\x0bGetProducts\x12\x0e.grocery.Query\x1a\x10.grocery.Resultsb\x06proto3')



_QUERY = DESCRIPTOR.message_types_by_name['Query']
_RESULTS = DESCRIPTOR.message_types_by_name['Results']
_RESULTS_PRODUCT = _RESULTS.nested_types_by_name['Product']
Query = _reflection.GeneratedProtocolMessageType('Query', (_message.Message,), {
  'DESCRIPTOR' : _QUERY,
  '__module__' : 'grocery_pb2'
  # @@protoc_insertion_point(class_scope:grocery.Query)
  })
_sym_db.RegisterMessage(Query)

Results = _reflection.GeneratedProtocolMessageType('Results', (_message.Message,), {

  'Product' : _reflection.GeneratedProtocolMessageType('Product', (_message.Message,), {
    'DESCRIPTOR' : _RESULTS_PRODUCT,
    '__module__' : 'grocery_pb2'
    # @@protoc_insertion_point(class_scope:grocery.Results.Product)
    })
  ,
  'DESCRIPTOR' : _RESULTS,
  '__module__' : 'grocery_pb2'
  # @@protoc_insertion_point(class_scope:grocery.Results)
  })
_sym_db.RegisterMessage(Results)
_sym_db.RegisterMessage(Results.Product)

_GROCERY = DESCRIPTOR.services_by_name['Grocery']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _QUERY._serialized_start=26
  _QUERY._serialized_end=54
  _RESULTS._serialized_start=57
  _RESULTS._serialized_end=198
  _RESULTS_PRODUCT._serialized_start=112
  _RESULTS_PRODUCT._serialized_end=198
  _GROCERY._serialized_start=200
  _GROCERY._serialized_end=258
# @@protoc_insertion_point(module_scope)
